# 部署配置文件
APP_NAME="pixelpunk"
VERSION="1.0.0"
REMOTE_USER="root"
REMOTE_HOST=""
REMOTE_PORT="22"
REMOTE_DIR="/www/wwwroot/dev.pixelpunk.cc"
SSH_KEY=""
KEEP_RELEASES=2
ENV_MODE="dev"
CONFIG_FILE_PATH="./configs/config.dev.yaml"
